PATCH http://localhost:3001/tasks
Content-Type: application/json

{
  "_id": "689baf5d05d0efbbf4eec4ab",
  "title": "Updated Task2",
  "dueDate" : "2025-01-01T12:00:00Z",
  "description": "a long list of description",
  "priority" : "normal",
  "status": "todo"
}